name = "Clarity"
license = "MIT"
licenselink = "https://github.com/chipzoller/hugo-clarity/blob/master/LICENSE.md"
description = "Security Architecture Site"
homepage = "https://github.com/chipzoller/hugo-clarity"
demosite = "https://neonmirrors.net/"
tags = ["blog", "technical", "simple", "dark", "syntax highlighting"]
features = ["blog", "technical", "simple", "dark", "syntax highlighting"]
min_version = "0.128.0"

# If the theme has multiple authors
authors = [
  {name = "Chip Zoller", homepage = "https://neonmirrors.net"},
  {name = "Dan Weru", homepage = "https://github.com/onweru"},
  {name = "Ivan Boothe", homepage = "https://rootwork.org"},
]
